---

- name: Install Docker
  hosts: all
  become: true
  tasks:

    # - name: Copy ELK Docker folder to Elastic node
    #   copy:
    #     src: /home/ubuntu/ansible-startup/docker-elk
    #     dest: /home/ubuntu/
    #     owner: ubuntu
    #     group: ubuntu
    #     mode: '0755'
    #     remote_src: no
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Clone ELK Docker repository
      git:
        repo: https://github.com/deviantony/docker-elk.git
        dest: /home/ubuntu/docker-elk
        update: yes

    # - name: Ensure Docker is installed
    #   apt:
    #     name: docker.io
    #     state: present
    #   become: true

    - name: Start ELK stack setup with Docker Compose
      command: docker compose up setup
      args:
        chdir: /home/ubuntu/docker-elk
      register: setup_result

    - name: Check if setup completed successfully
      debug:
        var: setup_result.stdout_lines

    - name: Start ELK stack with Docker Compose
      command: docker compose up -d
      args:
        chdir: /home/ubuntu/docker-elk
      become: true

    - name: Wait for Kibana to become available
      wait_for:
        host: localhost
        port: 5601
        timeout: 300